/*************************************************************************
 * This file was generated by CRUST by an automated semantics preserving
 * translation from C/C++ to Rust
 * CRUST isn't perfect and may require manual editing
 * Check warnings and errors and refer to the official Rust Documentation
 ************************************************************************/
package main

///////////////////////////////////////////////////////////////////
// 函 数 名：OnDayKline()
// 功能说明：转换K线类型的菜单命令处理
// 入口参数：无
// 返回参数：无返回数
/////////////////////////////////////////////////////////////////////////////
func (v *CTaiShanKlineShowView) OnDayKline() {
	v.m_nKlineKind2 = 5
	v.bTrackCurcorBgn = false
	var r = CRect{}
	v.GetClientRect(r)
	v.OnSizeMy(r.right-r.left, r.bottom-r.top)
	v.ShowAll(v.m_sharesSymbol)
}
